# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CatalystX-ListFramework-Builder
version:      0.18
version_from: lib/CatalystX/ListFramework/Builder.pm
installdirs:  site
requires:
    Catalyst::Model::DBIC::Schema: 0
    Catalyst::Runtime:             5.7
    Catalyst::View::JSON:          0
    Catalyst::View::TT:            0
    Class::C3:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
