--- #YAML:1.0
# you probably want to change these two values
base: "http://mywebserver.example.com"
javascript: "/static/javascript/ext-2.1"

# also change the path to the sqlite file you created with bootstrap_sqlite.pl
# and the schema name used as well
Model::DBIC:
  schema_class: TestApp::Schema
  connect_info:
     - "dbi:SQLite:dbname=__listframework_testapp.sqlite"
     - ""
     - ""
     - { AutoCommit: 1 }
